server.port=8080
spring.application.name=Nhom1_HTDiemDanh
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QLDiemDanh;encrypt=true;trustServerCertificate=true;

# THAY ĐỔI 2 DÒNG NÀY THÀNH TÀI KHOẢN SQL SERVER CỦA EM NHÉ:
spring.datasource.username=sa
spring.datasource.password=123456aA@$

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==========================================
# CẤU HÌNH JPA (TỰ ĐỘNG MAP DATABASE)
# ==========================================
# Hiện câu lệnh SQL ra màn hình Console để dễ debug (sửa lỗi)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CỰC KỲ QUAN TRỌNG: Để 'none' vì database em đã vẽ và tạo bảng sẵn rồi.
# Nếu để 'update' hay 'create', Spring Boot có thể sẽ làm loạn cấu trúc bảng của em.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl